### PR TITLE
WebEx Template and bulk recording deletion

### PR DESCRIPTION
**Pull request by programming2web**
Allows to indicate a standard template from WebEx to control new
meetings settings such as audio conference, attendee privileges,
meeting options, etc.

Adds a column with checkboxes to admin Manage Recordings page which
allows to bulk delete the selected recordings.

### CODE REVIEW

**Comment by merrill-oakland** [comment]
Thanks @programming2web! Sorry for the long delay.

Initial look is good, except the bulk delete needs to have logging implemented (and indent level fixed) where your todo it.

**Comment by programming2web** [comment]
Thanks, Eric!
I've added logging and fixed indentation. Also added a course column to admin recordings list as it is helpful to see that info besides recording name when deciding which recordings to delete.

**Comment by merrill-oakland** [comment]
I've merged your first 3 commits into master. The indenting still looks messed up in your last commit (Moodle doesn't use tabs, it uses 4 spaces per indent), plus there were some other minor code style issues, so I fixed those as well.

I'll merge them into the release branches when I make a new release.

**Comment by programming2web** [comment]
Thank you, Eric! 
Appreciate your note about the indents, I'll use 4 spaces in the future.

**Pull request closed without merging**
